#include <geometry_msgs/msg/Vector3.idl>
#include <geometry_msgs/msg/Quaternion.idl>
#include <halodi_definitions/msg/Joint.idl>

module halodi_wbc_msgs {
    module msg {
        
    
        struct JointSpaceCommand
        {
            halodi_definitions::msg::Joint joint;
        
            double q_desired;
            double qd_desired;
            double qdd_desired;
            
            double stiffness;
            double damping;
        };
    };
};
