#ifndef __actionlib_msgs__msg__GoalStatusArray__idl__
#define __actionlib_msgs__msg__GoalStatusArray__idl__

#include "actionlib_msgs/msg/./GoalStatus.idl"
#include "std_msgs/msg/./Header.idl"
module actionlib_msgs
{
  module msg
  {
    

      @TypeCode(type="actionlib_msgs::msg::dds_::GoalStatusArray_")
      struct GoalStatusArray
      {
        /**
         * Stores the statuses for goals that are currently being tracked
         * by an action server
         */
        std_msgs::msg::Header header;
        sequence<actionlib_msgs::msg::GoalStatus> status_list;
      };
    };
  };


#endif
