module halodi_msgs {
    module msg {
    
        /**
          * Calibration information for a 1DOF joint.
          *
          */
        @TypeCode(type="halodi_msgs::msg::dds_::RobotJointCalibrationInfo_")
        struct RobotJointCalibrationInfo
        {
            string frame_id;
            double transmission_ratio;
            double measurement_offset;
        };
        
    };
};
