module halodi_definitions 
{
    module msg 
    {

        /**
         *
         *  List of Reference Frames in the controller
         *
         *
        **/
        module ReferenceFrame_Constants
        {
            
            /**
             * Robot world frame.
             *
             * Expressable in : YES
             * Controllable : NO
             */ 
            const uint8 WORLD = 0;
            
            /**
             * Pelvis (torso) of the robot. Origin is the intersection of the hip roll, pitch and yaw axes.
             *
             * Expressable in : YES
             * Controllable : Partial (z-height with respect to base expressed in world and orientation)
             */
            const uint8 PELVIS = 1;
            
            /**
             * Wheeled base frame of the robot. Origin is the intersection of the ankle roll and pitch axes.
             *
             * Expressable in : YES
             * Controllable : NO
             */
            const uint8 BASE = 2;
            
            /**
             * Left hand frame. Origin is the intersection of the left wrist roll, pitch and yaw axes
             *
             * Expressable in : YES
             * Controllable : YES
             */
            const uint8 LEFT_HAND = 3;
            
            /**
             * Left hand frame. Origin is the intersection of the right wrist roll, pitch and yaw axes
             *
             * Expressable in : YES
             * Controllable : YES
             */
            const uint8 RIGHT_HAND = 4;
            
            /**
             * Left hand frame. Origin is the intersection of the left wrist roll, pitch and yaw axes
             *
             * Expressable in : YES
             * Controllable : Partial (orientation pitch with respect to pelvis only)
             */
            const uint8 HEAD = 5;
        };
       
        @TypeCode(type="halodi_definitions::msg::dds_::ReferenceFrame_")
        struct ReferenceFrame
        {
            uint8 frame_id;
        };
        
    };
};
