#include <halodi_msgs/msg/RobotStatusLevel.idl>

module halodi_msgs {
    module msg {
    
        /**
          * Status of the battery
          *
          */
        @TypeCode(type="halodi_msgs::msg::dds_::Battery_")
        struct BatteryStatus
        {
            
            
            /**
             * Charge status of the battery
             * 
             * WARNING: The robot should be moved to a safe position to shutdown and charge as soon as possible. 
             * ERROR: The battery is empty. The robot will go in a safe pose to avoid falling down
             * CRITICAL: The battery management system (BMS) turned off the power and the robot fell over. Note: This is never transmitted.
             *
             */
            halodi_msgs::msg::RobotStatusLevel battery_status_level;
            
            
            /**
             * Current estimate of the battery voltage in Volts
             *
             */
            double battery_voltage;
            
            /**
             * Battery voltage when the robot will emit a warning
             * 
             * 
             *
             */
            double low_battery_voltage;
            
            /**
             * Battery voltage when the robot will shutdown
             * 
             */
            double shutdown_battery_voltage;
            
        };
        
    };
};
 
