

module halodi_msgs {
    module msg {
        
        module ControlInputState_Constants
        {
            /**
             * The controller is still starting. Control is not possible yet.
             *
             */
            const long WAITING_FOR_CONTROLLER_START = 0;
        
            /**
             * The controller is accepting commands normally.
             */
            const long ACCEPTING_COMMANDS = 1;
            
            /**
             * The robot is frozen and does not accept commands. 
             * 
             * Use the StopCommand CLEAR_MOTOR_FAULTS_AND_GO_TO_DEFAULT_POSE to exit this state to default pose
             * Use the StopCommand SHUTDOWN_ROBOT to turn off the motors and controller
             */
            const long FROZEN = 2;
            
            /**
             * The robot is clearing motor errors and moving to default pose.
             *
             */
            const long MOVING_TO_DEFAULT_POSE = 3;            
            
            /**
             * The robot is in default pose
             * 
             * Use the StopCommand RESUME_CONTROL to accept commands again
             * Use the StopCommand SHUTDOWN_ROBOT to turn off the motors and controller
             */
            const long DEFAULT_POSE = 4;
            
            /**
             * The robot has been turned off by an unrecoverable fault.
             * 
             * Note: This could be the user pressing the emergency stop.
             *
             */ 
            const long FAULTED = 5;
        };
        
        /**
          * State of the control input listener on the robot
          *
          */
        @TypeCode(type="halodi_msgs::msg::dds_::ControlInputState_")
        struct ControlInputState
        {   
            long state;
        };
    };
};
