#ifndef __halodi_msgs__msg__DrivingCommand__idl__
#define __halodi_msgs__msg__DrivingCommand__idl__


module halodi_msgs {
    module msg {
        struct DrivingCommand
        {
            double x_dot;
            double omega_z;
        };
    };
};

#endif
