
module halodi_msgs {
    module msg {
        @TypeCode(type="halodi_msgs::msg::dds_::DrivingCommand_")
        struct DrivingCommand
        {
            /**
              * Bypass the default lowpass filter the desired x_dot and omega_z
	      *
	      * Use with caution, this could result in the robot falling if large changes in input velocity are send to the robot.              
              * 
              */
            boolean bypass_input_filter;
            
            /**
              * Desired linear velocity
              *
              */
            double linear_velocity;
            
            /**
              * Desired angular velocity
              *
              */
            double angular_velocity;
        };
    };
};
