#include <sensor_msgs/msg/CameraInfo.idl>
#include <geometry_msgs/msg/TransformStamped.idl>

#include <halodi_msgs/msg/RobotLinkCalibrationInfo.idl>
#include <halodi_msgs/msg/RobotJointCalibrationInfo.idl>

module halodi_msgs {
    module msg {
    
        /**
          * Extrinsic calibration data.
          *
          */
        @TypeCode(type="halodi_msgs::msg::dds_::ExtrinsicCalibrationInfo_")
        struct ExtrinsicCalibrationInfo
        {
            sequence<sensor_msgs::msg::CameraInfo, 255> camera_infos;
            sequence<geometry_msgs::msg::TransformStamped, 255> sensor_transforms;

            sequence<halodi_msgs::msg::RobotLinkCalibrationInfo, 255> link_infos;
            sequence<halodi_msgs::msg::RobotJointCalibrationInfo, 255> joint_infos;
        };
        
    };
};
