#ifndef __halodi_msgs__msg__FeedbackParametersSE3__idl__
#define __halodi_msgs__msg__FeedbackParametersSE3__idl__

#include <geometry_msgs/msg/Vector3.idl>
#include <halodi_msgs/msg/FeedbackParameters3D.idl>

module halodi_msgs {
    module msg {
        /**
         * Feedback parameters for a SE3 system, consisting of a linear and angular part.
         *
         */
        struct FeedbackParametersSE3
        {
            halodi_msgs::msg::FeedbackParameters3D linear;
            halodi_msgs::msg::FeedbackParameters3D angular;
        };      
    };
};

#endif
