

module halodi_msgs {
    module msg {
        
        module JointName_Constants
        {
            const octet HIP_YAW = 0;
            const octet HIP_ROLL = 1;
            const octet HIP_PITCH = 2;
            const octet KNEE_PITCH = 3;
            const octet ANKLE_ROLL = 4;
            const octet ANKLE_PITCH = 5;
            
            const octet LEFT_SHOULDER_PITCH = 6;
            const octet LEFT_SHOULDER_ROLL = 7;
            const octet LEFT_SHOULDER_YAW = 8;
            const octet LEFT_ELBOW_PITCH = 9;
            const octet LEFT_ELBOW_YAW = 10;
            const octet LEFT_WRIST_PITCH = 11;
            const octet LEFT_WRIST_ROLL = 12;
            
            const octet RIGHT_SHOULDER_PITCH = 13;
            const octet RIGHT_SHOULDER_ROLL = 14;
            const octet RIGHT_SHOULDER_YAW = 15;
            const octet RIGHT_ELBOW_PITCH = 16;
            const octet RIGHT_ELBOW_YAW = 17;
            const octet RIGHT_WRIST_PITCH = 18;
            const octet RIGHT_WRIST_ROLL = 19;
            
            const octet NECK_PITCH = 20;
            
            const octet LEFT_WHEEL = 21;
            const octet RIGHT_WHEEL = 22;
        };
        

        @TypeCode(type="halodi_msgs::msg::dds_::JointName_")
        struct JointName
        {   
            octet joint_id;
        };
    };
};
