#ifndef __halodi_msgs__msg__JointSpaceCommand__idl__
#define __halodi_msgs__msg__JointSpaceCommand__idl__


#include <geometry_msgs/msg/Vector3.idl>
#include <geometry_msgs/msg/Quaternion.idl>
#include <halodi_msgs/msg/Joint.idl>

module halodi_msgs {
    module msg {
        
    
        struct JointSpaceCommand
        {
            halodi_msgs::msg::Joint joint;
        
            double q_desired;
            double qd_desired;
            double qdd_desired;
            
            double stiffness;
            double damping;
        };
    };
};

#endif
