#include <halodi_msgs/msg/JointName.idl>
#include <halodi_msgs/msg/RobotStatusLevel.idl>

module halodi_msgs {
    module msg {
        
        /**
         * Raw errors from the motor driver
         *
         */
        module MotorStatus_Constants
        {
            const octet NO_ERROR = 0;
            const octet FAULTED = 1;
            const octet MISSED_DEADLINE = 2;
            const octet AUX_ENCODER_WARNING = 3;
            const octet AUX_ENCODER_ERROR = 4;
            const octet MOTOR_ENCODER_WARNING = 5;
            const octet MOTOR_ENCODER_ERROR = 6;
            const octet OVER_TEMPERATURE = 7;
            const octet OVER_VOLTAGE = 8;
            const octet UNDER_VOLTAGE = 9;
            const octet ETHERCAT_FAULT = 10;
            const octet INVALID_STATE_TRANSITION = 11;
            
        };
        
    
        /**
          * Status of a motor
          *
          * This message is a custom type instead of DiagnosticsArray, due to the overhead of String based values inside the controller
          *
          */
        @TypeCode(type="halodi_msgs::msg::dds_::MotorStatus_")
        struct MotorStatus
        {
            /**
             * Current status level of the motor
             */
            halodi_msgs::msg::RobotStatusLevel status_level;
            
            /**
             * Joints controlled by this motor
             *
             */
            sequence<halodi_msgs::msg::JointName, 2> joints;
            
            /**
             * ID of the motor with respect to the transmission 
             * 
             * This is either 0 or 1
             *
             */
            octet motor_id;
            
            /**
             *
             * Safe Torque Off (STO) enabled status.
             *
             * If STO is enabled, the motor driver is unable to turn on.
             */
            boolean sto_enabled;
            
            
            /**
             * If statusLevel == WARNING: The motor exceeds the warning temperature
             * If statusLevel == ERROR: The motor exceeds the error temperature and has been shutdown.
             */
            boolean over_temperature;
                        
            /**
             *
             * Serial number of the motor.
             *
             */
            unsigned long motor_serial_number;
            
            /**
             * Serial number of the driver.
             *
             */
            unsigned long driver_serial_number;
            
            /**
             * Set to true when the motor is initialized and reporting data
             *
             */
            boolean motor_initialized;
            
        
            /**
             * Current temperature of the motor
             *
             */
            double motor_temperature;
            
            /**
             * Current temperature of the motor driver
             *
             */
            double driver_temperature;
            
            
            /**
             * Error state from the motor driver board.
             *
             */ 
            octet motor_error;
            
        };
        
    };
};
 
