#ifndef __halodi_msgs__msg__ReferenceFrame__idl__
#define __halodi_msgs__msg__ReferenceFrame__idl__


module halodi_msgs 
{
    module msg 
    {

        /**
         *
         *  List of Reference Frames in the controller
         *
         *
        **/
        module ReferenceFrame_Constants
        {
            
            /**
             * Robot world frame.
             *
             * Expressable in : YES
             * Controllable : NO
             */ 
            const octet WORLD = 0;
            
            /**
             * Pelvis (torso) of the robot. Origin is the intersection of the hip roll, pitch and yaw axes.
             *
             * Expressable in : YES
             * Controllable : Partial (z-height with respect to base expressed in world and orientation)
             */
            const octet PELVIS = 1;
            
            /**
             * Wheeled base frame of the robot. Origin is the intersection of the ankle roll and pitch axes.
             *
             * Expressable in : YES
             * Controllable : NO
             */
            const octet BASE = 2;
            
            /**
             * Left hand frame. Origin is the intersection of the left wrist roll, pitch and yaw axes
             *
             * Expressable in : YES
             * Controllable : YES
             */
            const octet LEFT_HAND = 3;
            
            /**
             * Left hand frame. Origin is the intersection of the right wrist roll, pitch and yaw axes
             *
             * Expressable in : YES
             * Controllable : YES
             */
            const octet RIGHT_HAND = 4;
            
            /**
             * Left hand frame. Origin is the intersection of the left wrist roll, pitch and yaw axes
             *
             * Expressable in : YES
             * Controllable : Partial (orientation pitch with respect to pelvis only)
             */
            const octet HEAD = 5;
        };
       
        @TypeCode(type="halodi_msgs::msg::dds_::ReferenceFrame_")
        struct ReferenceFrame
        {
            octet frame_id;
        };
        
    };
};

#endif
