#include <geometry_msgs/msg/Vector3.idl>


module halodi_msgs {
    module msg {
    
        @TypeCode(type="halodi_msgs::msg::dds_::SpatialAcceleration_")
        struct SpatialAcceleration
        {
            geometry_msgs::msg::Vector3 linear;
            geometry_msgs::msg::Vector3 angular;
        };
    };
};
