

#include <geometry_msgs/msg/Pose.idl>
#include <geometry_msgs/msg/Twist.idl>
#include <geometry_msgs/msg/Accel.idl>

#include <halodi_msgs/msg/FeedbackParametersSE3.idl>
#include <halodi_msgs/msg/JointSpaceCommand.idl>
#include <halodi_msgs/msg/ReferenceFrameName.idl>

module halodi_msgs {
    module msg {
    
        @TypeCode(type="halodi_msgs::msg::dds_::TaskSpaceCommand_")
        struct TaskSpaceCommand
        {
            /**
             * Body Frame: The reference frame to control.
             *
             * Valid options are all frames that are "Controllable"
             *
             */
            halodi_msgs::msg::ReferenceFrameName body_frame;
            
            /**
             * Base frame: The base frame of motion for the spatial motion vectors (Twist and Spatial Accelertion)
             *
             * See us.ihmc.mecano.spatial.interfaces.SpatialMotionBasics for a description how to use base_frame.
             *
             * Tip: Set base_frame to body_frame to allow setting linear and angular components instead of spatial motions
             *
             * Valid options are all frames that are "Expressable in"
             *
             */
            halodi_msgs::msg::ReferenceFrameName base_frame;
            
            /**
             * Expressed in frame: Origin of the command.
             *
             * Valid options are all frames that are "Expressable in"
             *
             */
            halodi_msgs::msg::ReferenceFrameName expressed_in_frame;
            
            
            /**
             * Align the orientation of the expressed in frame such that z-axis points up. 
             * 
             * The heading (also known as yaw or the rotation around the z-axis) and position match the expressed_in_frame.
             *
             * This can be useful for keeping an end effector aligned with gravity while moving.
             * 
             */
            boolean express_in_z_up;
            
            
            /**
             * 
             * Desired pose of the body frame
             *
             */
            geometry_msgs::msg::Pose pose;
            
            /**
             * Desired twist of the body frame.
             *
             * See us.ihmc.mecano.spatial.Twist for a description how this relates to body_frame, base_frame and expressed_in_frame
             *
             */
            geometry_msgs::msg::Twist twist;
            
            /**
             * Desired spatial acceleration of the body frame
             * 
             * See us.ihmc.mecano.spatial.SpatialAcceleration for a description how this relates to body_frame, base_frame and expressed_in_frame
             *
             */
            geometry_msgs::msg::Accel spatial_acceleration;
            
            
            /**
             *
             * Feedback parameters
             *
             * Optional. When not provided, default values are used
             *
             */
            sequence<halodi_msgs::msg::FeedbackParametersSE3, 1> feedback_parameters;
            
            
            /**
             * Nullspace joint configuration between current 
             *
             */
            sequence<halodi_msgs::msg::JointSpaceCommand, 7> nullspace_command;
            
        };
    };
};

