#include <geometry_msgs/msg/Pose.idl>
#include <geometry_msgs/msg/Twist.idl>

#include <halodi_msgs/msg/SpatialAcceleration.idl>
#include <halodi_msgs/msg/FeedbackParametersSE3.idl>
#include <halodi_msgs/msg/JointSpaceCommand.idl>
#include <halodi_msgs/msg/ReferenceFrame.idl>

module halodi_msgs {
    module msg {
    
        @TypeCode(type="halodi_msgs::msg::dds_::TaskSpaceCommand_")
        struct TaskSpaceCommand
        {
            /**
             * Body Frame: The reference frame to control.
             *
             * Valid options are all frames that are "Controllable"
             *
             */
            char body_frame;
            
            /**
             * Base frame: The base frame of motion for the spatial motion vectors (Twist and Spatial Accelertion)
             *
             * See us.ihmc.mecano.spatial.interfaces.SpatialMotionBasics for a description how to use base_frame.
             *
             * Tip: Set base_frame to body_frame to allow setting linear and angular components instead of spatial motions
             *
             * Valid options are all frames that are "Expressable in"
             *
             */
            char base_frame;
            
            /**
             * Expressed in frame: Origin of the command.
             *
             * Valid options are all frames that are "Expressable in"
             *
             */
            char expressed_in_frame;
            
            /**
             * 
             * Desired pose of the body frame
             *
             */
            geometry_msgs::msg::Pose pose;
            
            /**
             * Desired twist of the body frame.
             *
             * See us.ihmc.mecano.spatial.Twist for a description
             *
             */
            geometry_msgs::msg::Twist twist;
            
            /**
             * Desired spatial acceleration of the body frame
             * 
             * See us.ihmc.mecano.spatial.SpatialAcceleration
             *
             */
            halodi_msgs::msg::SpatialAcceleration spatial_acceleration;
            
            
            /**
             *
             * Feedback parameters
             *
             */
            halodi_msgs::msg::FeedbackParametersSE3 feedback_parameters;
            
            
            /**
             * Nullspace joint configuration between current 
             *
             */
            sequence<halodi_msgs::msg::JointSpaceCommand, 7> nullspace_command;
            
        };
    };
};
