#ifndef __geometry_msgs__msg__PoseWithCovarianceStamped__idl__
#define __geometry_msgs__msg__PoseWithCovarianceStamped__idl__

#include "geometry_msgs/msg/./PoseWithCovariance.idl"
#include "std_msgs/msg/./Header.idl"
module geometry_msgs
{
  module msg
  {
    

      /**
       * This expresses an estimated pose with a reference coordinate frame and timestamp
       */
      @TypeCode(type="geometry_msgs::msg::dds_::PoseWithCovarianceStamped_")
      struct PoseWithCovarianceStamped
      {
        std_msgs::msg::Header header;
        geometry_msgs::msg::PoseWithCovariance pose;
      };
    };
  };


#endif
